version: '3.7'

services:
    database:
      image: mongo:latest
      container_name: database
      environment: 
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
      volumes:
        - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      ports:
        - 27017:27017